### ISSUE TITLE
Getting Lexical error occurs when you have multiple conditions

### ISSUE THREAD

**Issue by deepaksingh007** [hirochachacha/graphql-assert-transformer#1]
Error: 

```
"Lexical error,   Encountered: \"m\" (109), after : \".\" at *unset*[line 10, column 93]"

```

GraphQl query: 

```
type Post @model {
	id: ID!
	title: String @assert(condition: ".length() > 3 && .matches(\"[a-zA-Z0-9]+\")")
}
```

**Comment by mjza** [comment]
I have the same problem, I don't know why they don't react.

**Comment by mjza** [comment]
The problem is on line 77:

```
const cond1 = condition.replace(/\B\.\B/g, val).replace(/(?=^|[^)\]}]\B)\./g, `${val}.`)
```
This can matches `.` only once at the beginning of the word!

**Comment by hirochachacha** [comment]
It seems that `/(?=^|[^)\]}]\B)\./g` should be `/(?<=^|[^)\]}]\B)\./g`.
Sorry for the delay and thank you for the investigation.

**Comment by mjza** [comment]
@hirochachacha Has it already published in npm?

**Comment by hirochachacha** [comment]
Yes, I did.
